=== chine007/game2d-analisis/Game2DAnalisis4/GameSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:game="http://www.games.exa.unicen.edu.ar/GameSchema" 
	targetNamespace="http://www.games.exa.unicen.edu.ar/GameSchema"
	elementFormDefault="qualified">
	
	<element name="gameProperties" type="game:xmlGameProperties"/>

	<complexType name="xmlGameProperties">
		<sequence>
			<element name="analizedProperties" type="string" minOccurs="0"/>
			<element name="filtering" type="game:xmlFiltering" minOccurs="0"/>
			<element name="discretization" type="game:xmlDiscretization" minOccurs="0"/>
		</sequence>
	</complexType>	
	
	<!--=========================================== 
					Filtering 
	============================================-->
	<complexType name="xmlFiltering">
		<sequence>
			<element name="filter" type="game:xmlFilter" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<complexType name="xmlFilter">
		<sequence>
			<element name="param" type="game:xmlParam" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="clazz" type="string" use="required"/>
	</complexType>
	
	<complexType name="xmlParam">
		<attribute name="name" type="string"/>
		<attribute name="value" type="anySimpleType" use="required"/>
	</complexType>
	
	<!--=========================================== 
					Discretization 
	============================================-->
	<complexType name="xmlDiscretization">
		<sequence>
			<element name="discretizer" type="game:xmlDiscretizer" minOccurs="0" maxOccurs="unbounded"/>
			<element name="property" type="game:xmlProperty" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<complexType name="xmlDiscretizer">
		<sequence>
			<element name="param" type="game:xmlParam" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="clazz" type="string" use="required"/>
		<attribute name="tags" type="string" use="required"/>
	</complexType>	
		
	<complexType name="xmlProperty">
		<sequence>
			<element name="interval" type="game:xmlInterval" maxOccurs="unbounded"/>
		</sequence>	
		<attribute name="name" type="string" use="required"/>
	</complexType>
	
	<complexType name="xmlInterval">
		<attribute name="from" type="float"/>
		<attribute name="to" type="float"/>
		<attribute name="tag" type="string" use="required"/>
	</complexType>
	
</schema>

=== chine007/game2d-analisis/Game2DAnalisis4/input/discretize/all.xml
<?xml version="1.0" encoding="UTF-8"?>
<gameProperties xmlns="http://www.games.exa.unicen.edu.ar/GameSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.games.exa.unicen.edu.ar/GameSchema ../../GameSchema.xsd">

	<!-- 
		Propiedades a utilizar para el analisis (archivos arff)
		
		a. No pongo CORRECTANSWERS e INCORRECTANSWERS porque RESULTWON y RESULTLOST dan mas informacion
		(ejemplo: cuando hay timeout CORRECTANSWERS=0-INCORRECTANSWERS=0 y RESULTWON=0-RESULTLOST=1   
		
	<analizedProperties>timesPlayed,timePlayed,result,level,resultWon,resultLost</analizedProperties>
	--> 
	<analizedProperties>result,timesPlayed,timePlayed,level</analizedProperties>

	<discretization>
		<!-- Matchea una propiedad con la clase encargada de discretizarla (discretizadores genericos) -->
		<discretizer name="timesPlayed" clazz="DiscretizerGeneral" tags="{Few,Many}"/>
		<discretizer name="timePlayed" clazz="DiscretizerGeneral" tags="{Low,High}"/>
		<discretizer name="level" clazz="DiscretizerGeneral" tags="{Low,Medium,High}"/>
		<discretizer name="result" clazz="DiscretizerGeneral" tags="{Lost,Tie,Won}"/>
		<discretizer name="resultWon" clazz="DiscretizerGeneral" tags="{Few,Many}"/>
		<discretizer name="resultLost" clazz="DiscretizerGeneral" tags="{Few,Many}"/>
		<discretizer name="correctAnswers" clazz="DiscretizerGeneral" tags="{Few,Many}"/>
		<discretizer name="incorrectAnswers" clazz="DiscretizerGeneral" tags="{Few,Many}"/>

		<!-- 	
		<discretizer name="timesPlayed" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="timePlayed" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="level" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="result" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="resultWon" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="resultLost" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="correctAnswers" clazz="DiscretizerNull" tags="numeric"/>
		<discretizer name="incorrectAnswers" clazz="DiscretizerNull" tags="numeric"/>
		 -->
		
		<!-- Definicion de discretizaciones genericas -->
		<property name="timesPlayed">
			<interval from="0" to="5" tag="Few"/>
			<interval from="6" tag="Many"/>
		</property>
		<property name="timePlayed">
			<interval from="0" to="32000" tag="Low"/>
			<interval from="32001" tag="High"/>
		</property>
		<property name="level">
			<interval from="0" to="4" tag="Low"/>
			<interval from="5" to="7" tag="Medium"/>
			<interval from="8" tag="High"/>
		</property>
		<property name="result">
			<interval to="-1" tag="Lost"/>
			<interval from="0" to="18" tag="Tie"/>
			<interval from="19" tag="Won"/>
		</property>

		<!-- No se tienen en cuenta -->		
		<property name="resultWon">
			<interval to="-1" tag="Few"/>
			<interval from="0" tag="Many"/>
		</property>
		<property name="resultLost">
			<interval to="-1" tag="Few"/>
			<interval from="0" tag="Many"/>
		</property>
		<property name="correctAnswers">
			<interval to="0" tag="Few"/>
			<interval from="1" tag="Many"/>
		</property>
		<property name="incorrectAnswers">
			<interval to="0" tag="Few"/>
			<interval from="1" tag="Many"/>
		</property>
	</discretization>
</gameProperties>

=== chine007/game2d-analisis/Game2DAnalisis4/input/discretize/frogs.xml
<?xml version="1.0" encoding="UTF-8"?>
<gameProperties xmlns="http://www.games.exa.unicen.edu.ar/GameSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.games.exa.unicen.edu.ar/GameSchema ../../GameSchema.xsd">

	<!-- 
		La propiedad LEVEL no tiene sentido
		No uso la propiedad result, uso resultWon y resultLost
	-->
	<analizedProperties>timesPlayed,timePlayed,resultWon,resultLost</analizedProperties>

	<discretization>
		<discretizer name="timesPlayed" clazz="DiscretizerGeneral" tags="{Few,Medium,Many}"/>
		<discretizer name="timePlayed" clazz="DiscretizerGeneral" tags="{Low,Medium,High}"/>
		<discretizer name="result" clazz="DiscretizerGeneral" tags="{Lost,Tie,Won}"/>
		<discretizer name="resultWon" clazz="DiscretizerGeneral" tags="{Few,Medium,Many}"/>
		<discretizer name="resultLost" clazz="DiscretizerGeneral" tags="{Few,Medium,Many}"/>
	
		<property name="timesPlayed">
			<interval to="1" tag="Few"/>
			<interval from="2" to="3" tag="Medium"/>
			<interval from="4" tag="Many"/>
		</property>
		<property name="timePlayed">
			<interval from="0" to="15000" tag="Low"/>
			<interval from="15001" to="40000" tag="Medium"/>
			<interval from="40001" tag="High"/>
		</property>
		<property name="result">
			<interval to="-3" tag="Lost"/>
			<interval from="-2" to="0" tag="Tie"/>
			<interval from="1" tag="Won"/>
		</property>
		<property name="resultWon">
			<interval to="0" tag="Few"/>
			<interval from="1" to="1" tag="Medium"/>
			<interval from="2" tag="Many"/>
		</property>
		<property name="resultLost">
			<interval to="0" tag="Few"/>
			<interval from="1" to="2" tag="Medium"/>
			<interval from="3" tag="Many"/>
		</property>
	</discretization>
</gameProperties>

=== chine007/game2d-analisis/Game2DAnalisis4/input/discretize/geometry.xml
<?xml version="1.0" encoding="UTF-8"?>
<gameProperties xmlns="http://www.games.exa.unicen.edu.ar/GameSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.games.exa.unicen.edu.ar/GameSchema ../../GameSchema.xsd">
	<discretization>
		<discretizer name="timesPlayed" clazz="DiscretizerGeneral" tags="{Few,Medium,Many}"/>
		<discretizer name="timePlayed" clazz="DiscretizerGeneral" tags="{Low,Medium,High}"/>

		<property name="timesPlayed">
			<interval from="0" to="2" tag="Few"/>
			<interval from="3" to="5" tag="Medium"/>
			<interval from="6" tag="Many"/>
		</property>
		<property name="level">
			<interval from="0" to="9" tag="Low"/>
			<interval from="10" to="12" tag="Medium"/>
			<interval from="13" tag="High"/>
		</property>
		<property name="timePlayed">
			<interval from="0" to="3999" tag="Low"/>
			<interval from="4000" to="6000" tag="Medium"/>
			<interval from="6001" tag="High"/>
		</property>
	</discretization>
</gameProperties>

=== chine007/game2d-analisis/Game2DAnalisis4/input/discretize/fourknights.xml
<?xml version="1.0" encoding="UTF-8"?>
<gameProperties xmlns="http://www.games.exa.unicen.edu.ar/GameSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.games.exa.unicen.edu.ar/GameSchema ../../GameSchema.xsd">

	<!-- 
		La propiedad LEVEL no tiene sentido 
		<analizedProperties>timesPlayed,timePlayed,result,resultWon,resultLost</analizedProperties>
	-->
	<analizedProperties>timesPlayed,timePlayed,result</analizedProperties>

	<discretization>
		<discretizer name="timesPlayed" clazz="DiscretizerGeneral" tags="{Few,Many}"/>
		<discretizer name="timePlayed" clazz="DiscretizerGeneral" tags="{Low,Medium,High}"/>
		<discretizer name="result" clazz="DiscretizerGeneral" tags="{Lost,Medium,Won}"/>
	
		<property name="timesPlayed">
			<interval to="3" tag="Few"/>
			<interval from="4" tag="Many"/>
		</property>	
		<property name="timePlayed">
			<interval from="0" to="55000" tag="Low"/>
			<interval from="55001" to="75000" tag="Medium"/>
			<interval from="75001" tag="High"/>
		</property>
		<property name="result">
			<interval to="-1" tag="Lost"/>
			<interval from="0" to="2" tag="Medium"/>
			<interval from="3" tag="Won"/>
		</property>
	</discretization>
</gameProperties>

=== chine007/game2d-analisis/Game2DAnalisis4/input/5-bayes/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<gameProperties xmlns="http://www.games.exa.unicen.edu.ar/GameSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.games.exa.unicen.edu.ar/GameSchema ../../GameSchema.xsd">
	<discretization>
		<discretizer name="class" clazz="DiscretizerGeneral" tags="{VeryHigh,High,Neutral,Low,VeryLow}"/>
		<property name="class">
			<interval from="-11" to="-9" tag="VeryLow"/>
			<interval from="-7" to="-5" tag="Low"/>
			<interval from="-3" to="-1" tag="Neutral"/>
			<interval from="1" to="3" tag="Neutral"/>
			<interval from="5" to="7" tag="High"/>
			<interval from="9" to="11" tag="VeryHigh"/>
		</property>		
	</discretization>
</gameProperties>
